name: homzes_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.3
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash_icon.png
  android_12:
    image: assets/splash_icon.png
    color: "#FFFFFF"
  fullscreen: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#FFF0F298"
  adaptive_icon_foreground: "assets/app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
